apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - elasticsearch/credentials-secret.yaml
  - elasticsearch/service.yaml
  - elasticsearch/statefulset.yaml
  - kibana/deployment.yaml
  - kibana/service.yaml
  - kibana/init-job.yaml
  - fluentd/rbac.yaml
  - fluentd/configmap.yaml
  - fluentd/daemonset.yaml
  - fluentd/service.yaml
  - ingress.yaml
