apiVersion: v1
kind: ConfigMap
metadata:
  name: zord-aws-config
data:
  AWS_REGION: ap-south-1
  AWS_EC2_METADATA_DISABLED: "true"
  KAFKA_BROKERS: zord-kafka:9092
  DB_HOST: zord-postgres
  DB_PORT: "5432"
  DB_SSLMODE: disable
  OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector.tracing.svc.cluster.local:4317
