apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zord-edge-signing-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: zord-edge-signing-key
    creationPolicy: Owner
  data:
    - secretKey: ed25519_private.pem
      remoteRef:
        key: production/zord/edge-signing-key
        property: ed25519_private.pem
