apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zord-app-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: zord-app-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: zord/app-secrets
