apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: logging
  labels:
    app: elasticsearch
type: Opaque
stringData:
  # Change these before deploying to production
  ELASTIC_USERNAME: elastic
  ELASTIC_PASSWORD: zord-elastic-2026
