apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-dsn
  namespace: monitoring
type: Opaque
stringData:
  DATA_SOURCE_NAME: "postgresql://postgres:arealis_password@zord-postgres.zord.svc.cluster.local:5432/postgres?sslmode=disable"
