'use client'

import { useState } from 'react'
import { evidenceCopy } from '../../copy/evidenceCopy'
import { EVIDENCE_CARD } from '../../evidencePageTokens'
import { EvidenceSectionHeader } from '../EvidenceSectionHeader'

type EvidenceExportCenterProps = {
  defaultPackId?: string
}

const inputClass =
  'h-10 w-full max-w-md rounded-xl border border-slate-200 bg-white px-3 font-mono text-[14px] text-slate-900 shadow-sm outline-none focus:border-[#4a6fe6]/50 focus:ring-2 focus:ring-[#4a6fe6]/15'

const btnOutline =
  'rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-[13px] font-semibold text-slate-800 shadow-sm transition hover:border-slate-300 hover:bg-slate-50'

export function EvidenceExportCenter({ defaultPackId = '' }: EvidenceExportCenterProps) {
  const [packId, setPackId] = useState(defaultPackId)
  const [message, setMessage] = useState<string | null>(null)
  const [exporting, setExporting] = useState<string | null>(null)

  const runExport = async (
    exportType: 'FINANCE_SUMMARY' | 'AUDIT_DETAILED' | 'BANK_PSP_PACK' | 'RAW_JSON',
    label: string,
  ) => {
    const id = packId.trim()
    if (!id) {
      setMessage('Enter a payment reference or evidence pack ID.')
      return
    }
    setExporting(exportType)
    try {
      const res = await fetch('/api/v1/dispute/export', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({
          payment_reference: id,
          dispute_reason: 'BENEFICIARY_SAYS_NOT_RECEIVED',
          export_type: exportType,
        }),
      })
      if (!res.ok) {
        const text = await res.text()
        setMessage(`${label}: ${text.slice(0, 220) || evidenceCopy.export.apiPending}`)
        return
      }
      const blob = await res.blob()
      const disposition = res.headers.get('content-disposition') || ''
      const match = disposition.match(/filename=\"?([^\";]+)\"?/i)
      const filename = match?.[1] || `evidence-export-${Date.now()}`
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = filename
      document.body.appendChild(a)
      a.click()
      a.remove()
      URL.revokeObjectURL(url)
      setMessage(`Downloaded ${filename}.`)
    } catch {
      setMessage(`${label}: ${evidenceCopy.export.apiPending}`)
    } finally {
      setExporting(null)
    }
  }

  return (
    <div className="space-y-5">
      <section className={EVIDENCE_CARD}>
        <EvidenceSectionHeader
          title={evidenceCopy.export.centerTitle}
          subtitle={evidenceCopy.export.centerSubtitle}
        />
        <div className="space-y-4 px-5 pb-5">
          <label className="block space-y-1.5">
            <span className="text-[11px] font-semibold uppercase tracking-[0.1em] text-slate-500">
              Evidence Pack ID
            </span>
            <input
              value={packId}
              onChange={(e) => setPackId(e.target.value)}
              placeholder="EP-…"
              className={inputClass}
            />
          </label>

          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              disabled={Boolean(exporting)}
              onClick={() => void runExport('FINANCE_SUMMARY', evidenceCopy.export.financePdf)}
              className={btnOutline}
            >
              {evidenceCopy.export.financePdf}
            </button>
            <button
              type="button"
              disabled={Boolean(exporting)}
              onClick={() => void runExport('AUDIT_DETAILED', evidenceCopy.export.auditPdf)}
              className={btnOutline}
            >
              {evidenceCopy.export.auditPdf}
            </button>
            <button
              type="button"
              disabled={Boolean(exporting)}
              onClick={() => void runExport('BANK_PSP_PACK', evidenceCopy.export.bankPack)}
              className={btnOutline}
            >
              {evidenceCopy.export.bankPack}
            </button>
            <button
              type="button"
              disabled={Boolean(exporting)}
              onClick={() => void runExport('RAW_JSON', evidenceCopy.export.rawJson)}
              className="rounded-xl px-4 py-2.5 text-[13px] font-semibold text-white shadow-md transition hover:opacity-95"
              style={{ background: 'linear-gradient(135deg,#103a9e 0%,#00239c 100%)' }}
            >
              {evidenceCopy.export.rawJson}
            </button>
          </div>

          {message ? (
            <p className="rounded-lg border border-slate-100 bg-slate-50 px-3 py-2 text-[13px] font-medium text-[#00239C]">
              {message}
            </p>
          ) : null}

          <p className="max-w-2xl text-[12px] leading-relaxed text-slate-500">
            Exports are generated by{' '}
            <code className="font-mono text-[11px] text-slate-700">POST /api/v1/dispute/export</code>{' '}
            with tenant-scoped evidence permissions.
          </p>
        </div>
      </section>
    </div>
  )
}
