apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - jaeger/credentials-secret.yaml
  - otel-collector/configmap.yaml
  - otel-collector/deployment.yaml
  - otel-collector/service.yaml
  - jaeger/deployment.yaml
  - jaeger/service.yaml
  - ingress.yaml
