apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zord-public
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\":80},{\"HTTPS\":443}]"
    alb.ingress.kubernetes.io/certificate-arn: _domainconnect.domains.squarespace.com
    alb.ingress.kubernetes.io/ssl-redirect: "443"
spec:
  ingressClassName: alb
  rules:
    - host: zordnet.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zord-console
                port:
                  number: 3000
    - host: api.zordnet.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zord-edge
                port:
                  number: 8080
