apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
      - name: Elasticsearch
        type: elasticsearch
        access: proxy
        url: http://elasticsearch.logging.svc.cluster.local:9200
        database: "zord-logs-*"
        jsonData:
          timeField: "@timestamp"
          esVersion: "8.13.0"
          logMessageField: log
          logLevelField: stream
      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger-query.tracing.svc.cluster.local:16686
