apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: monitoring
  labels:
    app: grafana
type: Opaque
stringData:
  # Change these before deploying to production
  ADMIN_USER: admin
  ADMIN_PASSWORD: zord-grafana-2026
