/** Customer-facing copy for Settlement Journal (bank/PSP outcomes). */

export const settlementJournalCopy = {
  hero: {
    label: 'Observed Settlement Value',
    subtitle: 'Sum of observed amounts from settlement records',
  },
  kpi: {
    paymentPartner: 'Payment partner',
    paymentPartnerSub: 'Settlement source reported by bank or payment partner',
    recordsReceived: 'Settlement records received',
    recordsReceivedSub: (count: string) => `${count} settlement records in this batch`,
    settlementValueMatched: 'Settlement value matched',
    settlementValueMatchedSub: 'Bank-confirmed amount linked to payment instructions',
    amountVariance: 'Amount variance',
    amountVarianceSub: 'Linked via client ref or payment instruction',
    amountVarianceAwaiting: 'Variance appears once intelligence links settlement to instructions',
  },
  sidebar: {
    batchLabel: 'Batch',
    records: 'settlement records',
    observedValue: 'observed value',
    selectBatch: 'Select a batch from the sidebar',
  },
  tabs: {
    observations: 'Settlement Observations',
    parseErrors: 'Review Items',
  },
  table: {
    sourceRow: 'Source Row',
    clientRef: 'Client Ref',
    bankRef: 'Bank Ref / UTR',
    observedAmount: 'Observed Amount',
    netSettled: 'Net Settled',
    fee: 'Fee',
    sourceStatus: 'Source Status',
    matchStatus: 'Match Status',
    matchedPayment: 'Matched Payment',
    matchConfidence: 'Match Confidence',
    observedAt: 'Observed At',
    missingClientRef: 'Missing Client Ref',
    missingBankRef: 'Missing Bank Ref',
    searchPlaceholder: 'Search client ref, bank ref, amount, status…',
  },
  dataHealth: {
    title: 'Settlement Data Health',
    settlementParseIssues: 'Settlement parse issues',
    settlementParseIssuesSub: 'Rows that failed parsing or validation in the source file',
    withBankRef: 'Records with bank reference',
    withClientRef: 'Records with client reference',
    unmatchedSettlementValue: 'Unmatched settlement value',
    unmatchedSettlementValueSub: 'Settlement value not linked to a payment instruction',
    matchConfidence: 'Match confidence',
    missingRefRate: 'Missing reference rate',
    bankRefCoverageSub: 'From intelligence reference coverage',
    clientRefCoverageSub: 'From intelligence reference coverage',
  },
  netSettledNotProvided: 'Not provided in source file',
  export: {
    menuLabel: 'Export',
    records: 'Export settlement records',
    matchingReport: 'Export matching report',
    unmatchedOnly: 'Export unmatched only',
  },
} as const
