apiVersion: v1
kind: Service
metadata:
  name: kong-admin-ui
  namespace: api-gateway
  labels:
    app.kubernetes.io/name: kong-admin-ui
    app.kubernetes.io/component: admin-ui
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kong-admin-ui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
