apiVersion: v1
kind: Service
metadata:
  name: zord-prompt-layer-redis
spec:
  selector:
    app.kubernetes.io/name: zord-prompt-layer-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
