apiVersion: v1
kind: Service
metadata:
  name: konga
  namespace: api-gateway
  labels:
    app: konga
spec:
  selector:
    app: konga
  ports:
    - name: http
      port: 1337
      targetPort: 1337
      protocol: TCP
