apiVersion: v1
kind: Secret
metadata:
  name: jaeger-auth-credentials
  namespace: tracing
  labels:
    app: jaeger
type: Opaque
stringData:
  # Change these before deploying to production
  JAEGER_USERNAME: admin
  JAEGER_PASSWORD: zord-jaeger-2026
  # htpasswd format (SHA): admin / zord-jaeger-2026
  .htpasswd: "admin:{SHA}grxrhweS2FXRe9HjB6tofPYJhL8="
