import type {
  ActionRecommendation,
  ConnectorDrilldown,
  ConnectorHealthRow,
  CorrelationInsight,
  LeakageCompositionSlice,
  RoutingKpiSnapshot,
  RoutingTimeWindow,
  RouteRecommendationInput,
} from './types'

const CONNECTORS_24H: ConnectorHealthRow[] = [
  {
    id: 'rzp',
    connector: 'Razorpay',
    type: 'PSP',
    successPct: 97.8,
    avgTimeSec: 3.1,
    failurePct: 2.2,
    status: 'Healthy',
    trend: 'up',
    recommendedAction: 'Preferred PSP',
    volumeMinor: 3_100_000_000,
    moneyAtRiskMinor: 4_000_000,
    preventableLeakageMinor: 1_000_000,
  },
  {
    id: 'cashfree',
    connector: 'Cashfree',
    type: 'PSP',
    successPct: 95.2,
    avgTimeSec: 2.9,
    failurePct: 4.8,
    status: 'Degraded',
    trend: 'down',
    recommendedAction: 'Use fallback',
    volumeMinor: 1_900_000_000,
    moneyAtRiskMinor: 28_000_000,
    preventableLeakageMinor: 15_000_000,
  },
  {
    id: 'hdfc',
    connector: 'HDFC Bank',
    type: 'Bank',
    successPct: 98.4,
    avgTimeSec: 2.7,
    failurePct: 1.6,
    status: 'Healthy',
    trend: 'up',
    recommendedAction: 'Route traffic',
    volumeMinor: 1_600_000_000,
    moneyAtRiskMinor: 3_000_000,
    preventableLeakageMinor: 1_000_000,
  },
  {
    id: 'icici',
    connector: 'ICICI Bank',
    type: 'Bank',
    successPct: 94.8,
    avgTimeSec: 3.5,
    failurePct: 5.2,
    status: 'Risk',
    trend: 'down',
    recommendedAction: 'Avoid peak hours',
    volumeMinor: 1_300_000_000,
    moneyAtRiskMinor: 36_000_000,
    preventableLeakageMinor: 32_000_000,
  },
  {
    id: 'sbi',
    connector: 'SBI',
    type: 'Bank',
    successPct: 96.5,
    avgTimeSec: 4.1,
    failurePct: 3.5,
    status: 'Stable',
    trend: 'flat',
    recommendedAction: 'Use for NEFT',
    volumeMinor: 1_200_000_000,
    moneyAtRiskMinor: 5_000_000,
    preventableLeakageMinor: 4_000_000,
  },
  {
    id: 'upi',
    connector: 'UPI',
    type: 'Rail',
    successPct: 97.1,
    avgTimeSec: 2.5,
    failurePct: 2.9,
    status: 'Healthy',
    trend: 'up',
    recommendedAction: 'Default rail',
    volumeMinor: 1_000_000_000,
    moneyAtRiskMinor: 6_000_000,
    preventableLeakageMinor: 5_000_000,
  },
  {
    id: 'imps',
    connector: 'IMPS',
    type: 'Rail',
    successPct: 95.9,
    avgTimeSec: 2.2,
    failurePct: 4.1,
    status: 'Load',
    trend: 'down',
    recommendedAction: 'Avoid 6–8 PM',
    volumeMinor: 700_000_000,
    moneyAtRiskMinor: 29_000_000,
    preventableLeakageMinor: 12_000_000,
  },
  {
    id: 'neft',
    connector: 'NEFT',
    type: 'Rail',
    successPct: 96.8,
    avgTimeSec: 5.0,
    failurePct: 3.2,
    status: 'Reliable',
    trend: 'flat',
    recommendedAction: 'High-value use',
    volumeMinor: 600_000_000,
    moneyAtRiskMinor: 7_000_000,
    preventableLeakageMinor: 7_000_000,
  },
  {
    id: 'payu',
    connector: 'PayU',
    type: 'PSP',
    successPct: 92.5,
    avgTimeSec: 3.3,
    failurePct: 7.5,
    status: 'Stable',
    trend: 'flat',
    recommendedAction: 'Monitor retries',
    volumeMinor: 250_000_000,
    moneyAtRiskMinor: 2_000_000,
    preventableLeakageMinor: 1_000_000,
  },
  {
    id: 'axis',
    connector: 'Axis Bank',
    type: 'Bank',
    successPct: 92.2,
    avgTimeSec: 3.7,
    failurePct: 7.8,
    status: 'Stable',
    trend: 'flat',
    recommendedAction: 'Use in fallback chain',
    volumeMinor: 220_000_000,
    moneyAtRiskMinor: 1_500_000,
    preventableLeakageMinor: 1_000_000,
  },
  {
    id: 'kotak',
    connector: 'Kotak',
    type: 'Bank',
    successPct: 93.1,
    avgTimeSec: 3.9,
    failurePct: 6.9,
    status: 'Stable',
    trend: 'flat',
    recommendedAction: 'Throttle during spike windows',
    volumeMinor: 180_000_000,
    moneyAtRiskMinor: 1_000_000,
    preventableLeakageMinor: 1_000_000,
  },
  {
    id: 'yes',
    connector: 'Yes Bank',
    type: 'Bank',
    successPct: 91.9,
    avgTimeSec: 4.2,
    failurePct: 8.1,
    status: 'Stable',
    trend: 'down',
    recommendedAction: 'Route only secondary traffic',
    volumeMinor: 120_000_000,
    moneyAtRiskMinor: 500_000,
    preventableLeakageMinor: 500_000,
  },
  {
    id: 'rtgs',
    connector: 'RTGS',
    type: 'Rail',
    successPct: 93.4,
    avgTimeSec: 5.4,
    failurePct: 6.6,
    status: 'Stable',
    trend: 'flat',
    recommendedAction: 'Use for urgent high-value settlements',
    volumeMinor: 90_000_000,
    moneyAtRiskMinor: 500_000,
    preventableLeakageMinor: 500_000,
  },
  {
    id: 'nach',
    connector: 'NACH',
    type: 'Rail',
    successPct: 92.8,
    avgTimeSec: 4.8,
    failurePct: 7.2,
    status: 'Stable',
    trend: 'flat',
    recommendedAction: 'Use non-urgent queue',
    volumeMinor: 140_000_000,
    moneyAtRiskMinor: 500_000,
    preventableLeakageMinor: 0,
  },
]

const ROUTE_CANDIDATES_24H: RouteRecommendationInput[] = [
  {
    id: 'route-rzp-upi-hdfc',
    psp: 'Razorpay',
    rail: 'UPI',
    bank: 'HDFC',
    successRatePct: 98.2,
    avgTimeSec: 3.2,
    risk: 'Low',
    leakageSavingsMinor: 32_000_000,
    sampleSize: 14_500,
    stabilityScore: 92,
    failureTrendPenalty: 8,
    missingSignals: 0,
  },
  {
    id: 'route-cf-imps-icici',
    psp: 'Cashfree',
    rail: 'IMPS',
    bank: 'ICICI',
    successRatePct: 97.5,
    avgTimeSec: 2.8,
    risk: 'Medium',
    leakageSavingsMinor: 21_000_000,
    sampleSize: 8_200,
    stabilityScore: 79,
    failureTrendPenalty: 18,
    missingSignals: 1,
  },
  {
    id: 'route-rzp-neft-sbi',
    psp: 'Razorpay',
    rail: 'NEFT',
    bank: 'SBI',
    successRatePct: 96.9,
    avgTimeSec: 5.1,
    risk: 'Low',
    leakageSavingsMinor: 9_000_000,
    bestForHighValue: true,
    sampleSize: 2_950,
    stabilityScore: 88,
    failureTrendPenalty: 12,
    missingSignals: 2,
  },
  {
    id: 'route-payu-upi-icici',
    psp: 'PayU',
    rail: 'UPI',
    bank: 'ICICI',
    successRatePct: 93.3,
    avgTimeSec: 3.4,
    risk: 'High',
    leakageSavingsMinor: 4_000_000,
    sampleSize: 2_100,
    stabilityScore: 64,
    failureTrendPenalty: 28,
    missingSignals: 2,
  },
  {
    id: 'route-cf-neft-axis',
    psp: 'Cashfree',
    rail: 'NEFT',
    bank: 'Axis',
    successRatePct: 94.1,
    avgTimeSec: 4.8,
    risk: 'Medium',
    leakageSavingsMinor: 6_000_000,
    sampleSize: 4_100,
    stabilityScore: 70,
    failureTrendPenalty: 20,
    missingSignals: 1,
  },
]

const CORRELATION_INSIGHTS: CorrelationInsight[] = [
  { id: 'insight-icici-upi', text: 'ICICI + UPI → 3x higher failure rate.' },
  { id: 'insight-imps-peak', text: 'IMPS failures spike between 6 PM – 8 PM.' },
  { id: 'insight-cf-sbi', text: 'Cashfree + SBI improves retry success by 12%.' },
  { id: 'insight-neft-high-value', text: 'High-value payments (>₹50K) perform better on NEFT.' },
]

const ACTION_RECOMMENDATIONS: ActionRecommendation[] = [
  {
    id: 'action-avoid-icici-upi',
    title: 'Avoid ICICI via UPI during peak hours',
    impactMinor: 32_000_000,
    impactLabel: 'Prevent ₹3.2L loss',
  },
  {
    id: 'action-reduce-retries',
    title: 'Reduce retries after 1 attempt',
    impactMinor: 21_000_000,
    impactLabel: 'Prevent ₹2.1L waste',
  },
  {
    id: 'action-neft-high-value',
    title: 'Route high-value payments via NEFT',
    impactMinor: 9_000_000,
    impactLabel: 'Improve success rate',
  },
  {
    id: 'action-rzp-upi',
    title: 'Switch PSP to Razorpay for UPI flows',
    impactMinor: 19_000_000,
    impactLabel: 'Increase success by 2.3%',
  },
]

const LEAKAGE_COMPOSITION: LeakageCompositionSlice[] = [
  { key: 'unmatched', label: 'Unmatched', amountMinor: 380_000_00 },
  { key: 'short_settled', label: 'Short settled', amountMinor: 420_000_00 },
  { key: 'unlinked', label: 'Unlinked', amountMinor: 220_000_00 },
  { key: 'reversal', label: 'Reversal', amountMinor: 220_000_00 },
]

const NETWORK_HEALTH_TREND: RoutingKpiSnapshot['networkHealthTrend'] = [
  { label: 'D-6', successPct: 95.9, latencyIndex: 74 },
  { label: 'D-5', successPct: 96.1, latencyIndex: 73 },
  { label: 'D-4', successPct: 96.0, latencyIndex: 76 },
  { label: 'D-3', successPct: 96.3, latencyIndex: 71 },
  { label: 'D-2', successPct: 96.5, latencyIndex: 69 },
  { label: 'D-1', successPct: 96.2, latencyIndex: 72 },
  { label: 'Today', successPct: 96.4, latencyIndex: 70 },
]

const DRILLDOWNS: ConnectorDrilldown[] = [
  {
    connectorId: 'icici',
    successTrend7d: [
      { day: 'D-6', successPct: 95.2 },
      { day: 'D-5', successPct: 95.1 },
      { day: 'D-4', successPct: 94.9 },
      { day: 'D-3', successPct: 94.8 },
      { day: 'D-2', successPct: 94.7 },
      { day: 'D-1', successPct: 94.8 },
      { day: 'Today', successPct: 94.8 },
    ],
    topFailures: [
      { reason: 'Timeout', pct: 35 },
      { reason: 'Bank Reject', pct: 28 },
      { reason: 'Reconciliation Miss', pct: 21 },
    ],
    bestPairings: ['NEFT', 'RTGS'],
    weakPairings: ['UPI'],
    suggested: 'Avoid during peak hours',
  },
  {
    connectorId: 'cashfree',
    successTrend7d: [
      { day: 'D-6', successPct: 96.2 },
      { day: 'D-5', successPct: 95.9 },
      { day: 'D-4', successPct: 95.7 },
      { day: 'D-3', successPct: 95.5 },
      { day: 'D-2', successPct: 95.4 },
      { day: 'D-1', successPct: 95.2 },
      { day: 'Today', successPct: 95.2 },
    ],
    topFailures: [
      { reason: 'Webhook Delay', pct: 33 },
      { reason: 'Session Timeout', pct: 26 },
      { reason: 'Decline Burst', pct: 19 },
    ],
    bestPairings: ['SBI', 'NEFT'],
    weakPairings: ['IMPS (6–8 PM)'],
    suggested: 'Use fallback PSP during IMPS peak',
  },
  {
    connectorId: 'rzp',
    successTrend7d: [
      { day: 'D-6', successPct: 97.2 },
      { day: 'D-5', successPct: 97.4 },
      { day: 'D-4', successPct: 97.6 },
      { day: 'D-3', successPct: 97.7 },
      { day: 'D-2', successPct: 97.8 },
      { day: 'D-1', successPct: 97.8 },
      { day: 'Today', successPct: 97.8 },
    ],
    topFailures: [
      { reason: 'Bank Timeout', pct: 29 },
      { reason: 'Issuer Reject', pct: 25 },
      { reason: 'Auth Drop', pct: 18 },
    ],
    bestPairings: ['UPI', 'HDFC'],
    weakPairings: ['NACH'],
    suggested: 'Use as primary PSP for UPI',
  },
]

export function getSeededRoutingSnapshot(window: RoutingTimeWindow): RoutingKpiSnapshot {
  const generatedAt = new Date(Date.now() - 10 * 60 * 1000).toISOString()

  if (window === '24h') {
    return {
      generatedAtIso: generatedAt,
      staleAfterMinutes: 30,
      connectors: CONNECTORS_24H,
      routeCandidates: ROUTE_CANDIDATES_24H,
      correlationInsights: CORRELATION_INSIGHTS,
      actionRecommendations: ACTION_RECOMMENDATIONS,
      leakageComposition: LEAKAGE_COMPOSITION,
      networkHealthTrend: NETWORK_HEALTH_TREND,
      drilldowns: DRILLDOWNS,
    }
  }

  const multiplier = window === '7d' ? 7 : 30
  return {
    generatedAtIso: generatedAt,
    staleAfterMinutes: 30,
    connectors: CONNECTORS_24H.map((row) => ({
      ...row,
      volumeMinor: row.volumeMinor * multiplier,
      moneyAtRiskMinor: row.moneyAtRiskMinor * Math.max(1, Math.round(multiplier * 0.8)),
      preventableLeakageMinor: row.preventableLeakageMinor * Math.max(1, Math.round(multiplier * 0.78)),
    })),
    routeCandidates: ROUTE_CANDIDATES_24H,
    correlationInsights: CORRELATION_INSIGHTS,
    actionRecommendations: ACTION_RECOMMENDATIONS,
    leakageComposition: LEAKAGE_COMPOSITION.map((slice) => ({
      ...slice,
      amountMinor: slice.amountMinor * Math.max(1, Math.round(multiplier * 0.75)),
    })),
    networkHealthTrend: NETWORK_HEALTH_TREND,
    drilldowns: DRILLDOWNS,
  }
}
