package persistence

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// IntelligenceSnapshotRepo handles all DB operations for the intelligence_snapshots table.
//
// WHAT IS AN INTELLIGENCE SNAPSHOT?
// A snapshot is a materialised, explainable intelligence bundle per tenant/scope/window.
// It is the decoupling layer between "projection math" (projection_state rows) and
// "customer-facing intelligence view" (what the dashboard shows).
//
// One snapshot = one complete answer to one intelligence question.
// Example: "What was the LEAKAGE for tenant tnt_A across all corridors in the last 24h?"
//
// WHY A SEPARATE TABLE FROM projection_state?
// projection_state = raw incremental counters (updated on every event, never cleared)
// intelligence_snapshots = computed intelligence views (written on demand or schedule)
//
// This separation means:
//   - Dashboards read stable snapshot rows, not hot projection rows
//   - Snapshots can be versioned (model_version field) for A/B testing
//   - Explanations (intelligence_explanations table) reference snapshots, not raw projections
//   - Replay sandbox (Phase 2+) replays projections and diffs new snapshots

// IntelligenceSnapshot mirrors the intelligence_snapshots DB table.
type IntelligenceSnapshot struct {
	SnapshotID         string          `json:"snapshot_id"`
	TenantID           string          `json:"tenant_id"`
	SnapshotType       string          `json:"snapshot_type"`       // LEAKAGE | AMBIGUITY | DEFENSIBILITY | RCA | PATTERN | RECOMMENDATION
	ScopeType          string          `json:"scope_type"`          // TENANT | BATCH | CORRIDOR | PSP | SOURCE | INTENT
	ScopeRef           *string         `json:"scope_ref,omitempty"` // nil when scope_type = TENANT
	WindowStart        time.Time       `json:"window_start"`
	WindowEnd          time.Time       `json:"window_end"`
	ProjectionRefsJSON json.RawMessage `json:"projection_refs_json"`    // []string of projection IDs used
	SnapshotJSON       json.RawMessage `json:"snapshot_json"`           // the intelligence output
	ModelVersion       *string         `json:"model_version,omitempty"` // nil = deterministic
	CreatedAt          time.Time       `json:"created_at"`
}

// IntelligenceSnapshotRepo provides Create and Read operations for intelligence_snapshots.
type IntelligenceSnapshotRepo struct {
	pool *pgxpool.Pool
}

// NewIntelligenceSnapshotRepo creates an IntelligenceSnapshotRepo.
func NewIntelligenceSnapshotRepo(pool *pgxpool.Pool) *IntelligenceSnapshotRepo {
	return &IntelligenceSnapshotRepo{pool: pool}
}

// Create inserts a new intelligence snapshot.
//
// Called by Phase 4 intelligence layer services when they compute a new snapshot.
// The snapshot_id must be generated by the caller (use "snap_" + uuid).
//
// IMMUTABILITY: Snapshots are write-once. If a snapshot already exists for the
// same scope+type+window, the caller should generate a new snapshot_id rather
// than updating the old one. This preserves full history and supports diffing.
func (r *IntelligenceSnapshotRepo) Create(
	ctx context.Context,
	snap IntelligenceSnapshot,
) error {
	sql := `
		INSERT INTO intelligence_snapshots
			(snapshot_id, tenant_id, snapshot_type, scope_type, scope_ref,
			 window_start, window_end, projection_refs_json, snapshot_json,
			 model_version, created_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
	`
	if _, err := r.pool.Exec(ctx, sql,
		snap.SnapshotID,
		snap.TenantID,
		snap.SnapshotType,
		snap.ScopeType,
		snap.ScopeRef, // nullable
		snap.WindowStart,
		snap.WindowEnd,
		snap.ProjectionRefsJSON,
		snap.SnapshotJSON,
		snap.ModelVersion, // nullable
		snap.CreatedAt,
	); err != nil {
		return fmt.Errorf("intelligence_snapshot_repo.Create snap_id=%s type=%s: %w",
			snap.SnapshotID, snap.SnapshotType, err)
	}
	return nil
}

// GetByID returns one snapshot by its primary key.
// Returns nil, nil when no row exists.
func (r *IntelligenceSnapshotRepo) GetByID(
	ctx context.Context,
	snapshotID string,
) (*IntelligenceSnapshot, error) {
	sql := `
		SELECT snapshot_id, tenant_id, snapshot_type, scope_type, scope_ref,
		       window_start, window_end, projection_refs_json, snapshot_json,
		       model_version, created_at
		FROM   intelligence_snapshots
		WHERE  snapshot_id = $1
	`
	row := r.pool.QueryRow(ctx, sql, snapshotID)
	snap, err := scanSnapshot(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("intelligence_snapshot_repo.GetByID snap_id=%s: %w", snapshotID, err)
	}
	return snap, nil
}

// GetLatestByType returns the most recently created snapshot for a
// tenant + snapshot_type + scope combination.
//
// Used by the intelligence API handlers to serve the current intelligence state.
// Returns nil, nil when no snapshot exists yet (normal on fresh tenants).
func (r *IntelligenceSnapshotRepo) GetLatestByType(
	ctx context.Context,
	tenantID string,
	snapshotType string,
	scopeType string,
	scopeRef *string, // nil for TENANT scope
) (*IntelligenceSnapshot, error) {
	var sql string
	var args []any

	if scopeRef == nil {
		sql = `
			SELECT snapshot_id, tenant_id, snapshot_type, scope_type, scope_ref,
			       window_start, window_end, projection_refs_json, snapshot_json,
			       model_version, created_at
			FROM   intelligence_snapshots
			WHERE  tenant_id     = $1
			  AND  snapshot_type = $2
			  AND  scope_type    = $3
			  AND  scope_ref     IS NULL
			ORDER  BY created_at DESC
			LIMIT  1
		`
		args = []any{tenantID, snapshotType, scopeType}
	} else {
		sql = `
			SELECT snapshot_id, tenant_id, snapshot_type, scope_type, scope_ref,
			       window_start, window_end, projection_refs_json, snapshot_json,
			       model_version, created_at
			FROM   intelligence_snapshots
			WHERE  tenant_id     = $1
			  AND  snapshot_type = $2
			  AND  scope_type    = $3
			  AND  scope_ref     = $4
			ORDER  BY created_at DESC
			LIMIT  1
		`
		args = []any{tenantID, snapshotType, scopeType, *scopeRef}
	}

	row := r.pool.QueryRow(ctx, sql, args...)
	snap, err := scanSnapshot(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("intelligence_snapshot_repo.GetLatestByType type=%s scope=%s: %w",
			snapshotType, scopeType, err)
	}
	return snap, nil
}

// GetLatestByTypeAnyScope returns the most recently created snapshot for a
// tenant + snapshot_type + scope_type, ignoring scope_ref.
// Used by the Pattern handler when no specific batch_id is provided — shows the
// most recently scored batch regardless of which batch it was.
func (r *IntelligenceSnapshotRepo) GetLatestByTypeAnyScope(
	ctx context.Context,
	tenantID string,
	snapshotType string,
	scopeType string,
) (*IntelligenceSnapshot, error) {
	sql := `
		SELECT snapshot_id, tenant_id, snapshot_type, scope_type, scope_ref,
		       window_start, window_end, projection_refs_json, snapshot_json,
		       model_version, created_at
		FROM   intelligence_snapshots
		WHERE  tenant_id     = $1
		  AND  snapshot_type = $2
		  AND  scope_type    = $3
		ORDER  BY created_at DESC
		LIMIT  1
	`
	row := r.pool.QueryRow(ctx, sql, tenantID, snapshotType, scopeType)
	snap, err := scanSnapshot(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("intelligence_snapshot_repo.GetLatestByTypeAnyScope type=%s scope=%s: %w",
			snapshotType, scopeType, err)
	}
	return snap, nil
}

// ListByTenantAndType returns the N most recent snapshots for a tenant + type.
//
// Used by the replay sandbox and trend views to show history.
// limit controls how many rows to return (max 100 to protect the DB).
func (r *IntelligenceSnapshotRepo) ListByTenantAndType(
	ctx context.Context,
	tenantID string,
	snapshotType string,
	limit int,
) ([]IntelligenceSnapshot, error) {
	if limit <= 0 || limit > 100 {
		limit = 20 // safe default
	}

	sql := `
		SELECT snapshot_id, tenant_id, snapshot_type, scope_type, scope_ref,
		       window_start, window_end, projection_refs_json, snapshot_json,
		       model_version, created_at
		FROM   intelligence_snapshots
		WHERE  tenant_id     = $1
		  AND  snapshot_type = $2
		ORDER  BY created_at DESC
		LIMIT  $3
	`
	rows, err := r.pool.Query(ctx, sql, tenantID, snapshotType, limit)
	if err != nil {
		return nil, fmt.Errorf("intelligence_snapshot_repo.ListByTenantAndType type=%s: %w",
			snapshotType, err)
	}
	defer rows.Close()

	var result []IntelligenceSnapshot
	for rows.Next() {
		snap, err := scanSnapshotFromRows(rows)
		if err != nil {
			return nil, fmt.Errorf("intelligence_snapshot_repo.ListByTenantAndType scan: %w", err)
		}
		result = append(result, *snap)
	}
	return result, nil
}

// GetLatestByTypeFiltered returns the most recently created snapshot for a
// tenant + type + scope, with optional created_at date range filtering.
//
// Used by the dashboard endpoints which accept from_date / to_date query params.
// If from and to are nil this behaves identically to GetLatestByType.
func (r *IntelligenceSnapshotRepo) GetLatestByTypeFiltered(
	ctx context.Context,
	tenantID, snapshotType, scopeType string,
	scopeRef *string,
	from, to *time.Time,
) (*IntelligenceSnapshot, error) {
	base := `
		SELECT snapshot_id, tenant_id, snapshot_type, scope_type, scope_ref,
		       window_start, window_end, projection_refs_json, snapshot_json,
		       model_version, created_at
		FROM   intelligence_snapshots
		WHERE  tenant_id     = $1
		  AND  snapshot_type = $2
		  AND  scope_type    = $3
	`
	args := []any{tenantID, snapshotType, scopeType}
	argIdx := 4

	if scopeRef == nil {
		base += " AND scope_ref IS NULL"
	} else {
		base += fmt.Sprintf(" AND scope_ref = $%d", argIdx)
		args = append(args, *scopeRef)
		argIdx++
	}
	if from != nil {
		base += fmt.Sprintf(" AND created_at >= $%d", argIdx)
		args = append(args, *from)
		argIdx++
	}
	if to != nil {
		base += fmt.Sprintf(" AND created_at <= $%d", argIdx)
		args = append(args, *to)
		argIdx++
	}
	_ = argIdx
	base += " ORDER BY created_at DESC LIMIT 1"

	row := r.pool.QueryRow(ctx, base, args...)
	snap, err := scanSnapshot(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("intelligence_snapshot_repo.GetLatestByTypeFiltered type=%s scope=%s: %w",
			snapshotType, scopeType, err)
	}
	return snap, nil
}

// scanSnapshot scans one row from a QueryRow call into an IntelligenceSnapshot.
func scanSnapshot(row pgx.Row) (*IntelligenceSnapshot, error) {
	var s IntelligenceSnapshot
	err := row.Scan(
		&s.SnapshotID,
		&s.TenantID,
		&s.SnapshotType,
		&s.ScopeType,
		&s.ScopeRef,
		&s.WindowStart,
		&s.WindowEnd,
		&s.ProjectionRefsJSON,
		&s.SnapshotJSON,
		&s.ModelVersion,
		&s.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &s, nil
}

// scanSnapshotFromRows scans one row from a Query (rows) call.
func scanSnapshotFromRows(rows pgx.Rows) (*IntelligenceSnapshot, error) {
	var s IntelligenceSnapshot
	err := rows.Scan(
		&s.SnapshotID,
		&s.TenantID,
		&s.SnapshotType,
		&s.ScopeType,
		&s.ScopeRef,
		&s.WindowStart,
		&s.WindowEnd,
		&s.ProjectionRefsJSON,
		&s.SnapshotJSON,
		&s.ModelVersion,
		&s.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &s, nil
}
