# ─────────────────────────────────────────────────────────────────────────────
# SecretStore for api-gateway namespace — connects to AWS Secrets Manager
# ─────────────────────────────────────────────────────────────────────────────
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: api-gateway
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: zord-aws-access
