# ─────────────────────────────────────────────────────────────────────────────
# ServiceAccount for api-gateway namespace — IRSA for AWS access
# ─────────────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zord-aws-access
  namespace: api-gateway
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::522189039032:role/ZordAppS3AccessRole
